# Generated by Django 4.2.28 on 2026-03-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('area', models.CharField(max_length=191)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('social_status', models.CharField(max_length=191)),
                ('health_status', models.CharField(max_length=191)),
                ('sponsorship_status', models.CharField(default='Available', max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
