# Generated by Django 4.2.28 on 2026-03-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donor_sponsorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orphan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orphans/'),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='sponsorship_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sponsored', 'Sponsored')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
    ]
