# Generated by Django 4.2.29 on 2026-03-14 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_payment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.donor'),
        ),
        migrations.AddField(
            model_name='notification',
            name='orphan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orphan'),
        ),
    ]
