# Generated by Django 4.2.29 on 2026-03-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_donor_notification_orphan'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='orphan',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='orphan',
            name='health_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orphan',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
