# Generated by Django 4.2.28 on 2026-03-17 21:22

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_donor_user_orphan_user_orphan_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=core.models.orphan_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), core.models.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Bank', 'Bank'), ('PalPay', 'PalPay'), ('Cash', 'Cash'), ('Wallet', 'Wallet')], default='Cash', max_length=50),
        ),
    ]
