# Generated by Django 4.2.28 on 2026-03-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_payment_receipt_image_payment_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
