# Generated by Django 4.2.28 on 2026-03-17 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_donor_address_donor_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: شهادة مدرسية - الفصل الأول', max_length=200)),
                ('document', models.FileField(upload_to='orphan_docs/%Y/%m/')),
                ('document_type', models.CharField(choices=[('Legal', 'مستندات قانونية (هوية/شهادة ميلاد)'), ('Medical', 'تقارير طبية'), ('Education', 'شهادات مدرسية'), ('Media', 'صور وتحديثات عامة'), ('Other', 'أخرى')], default='Other', max_length=50)),
                ('is_public', models.BooleanField(default=False, help_text='تفعيل هذا الخيار سيسمح للكافل برؤية وتحميل هذا الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('orphan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_documents', to='core.orphan')),
            ],
        ),
    ]
