# Generated by Django 4.2.28 on 2026-03-21 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_orphandocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphan',
            name='sponsorship_status',
            field=models.CharField(choices=[('Pending', 'قيد مراجعة الإدارة'), ('Available', 'متاح للكفالة'), ('Sponsored', 'مكفول')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الوصي الرباعي')),
                ('id_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('relation_to_orphan', models.CharField(max_length=50, verbose_name='صلة القرابة (مثال: أم، عم، جد)')),
                ('legal_document', models.FileField(upload_to='guardian_docs/', verbose_name='مستند الوصاية')),
                ('payout_method', models.CharField(choices=[('Bank', 'حوالة بنكية'), ('Wallet', 'محفظة إلكترونية (مثل Jawwal Pay)'), ('Cash', 'استلام نقدي باليد')], default='Cash', max_length=20, verbose_name='طريقة استلام الكفالة')),
                ('payout_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الحساب أو رقم المحفظة')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تم التحقق من الوصي')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orphan',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orphans', to='core.guardian'),
        ),
    ]
