# Generated by Django 4.2.28 on 2026-03-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_orphan_sponsorship_status_guardian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphan',
            name='health_status',
            field=models.CharField(default='سليمة', max_length=100),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='social_status',
            field=models.CharField(default='غير محدد', max_length=100),
        ),
    ]
