# Generated by Django 4.2.28 on 2026-03-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_orphan_health_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='sponsorship_type',
            field=models.CharField(choices=[('Financial', 'Financial'), ('Educational', 'Educational'), ('Health', 'Health'), ('Monthly', 'Monthly')], default='Financial', max_length=50),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Ended', 'Ended')], default='Pending', max_length=50),
        ),
    ]
