# Generated by Django 4.2.28 on 2026-03-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sponsorship_sponsorship_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
