# Generated by Django 4.2.28 on 2026-03-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='guardian_ids/', verbose_name='صورة هوية الوصي للتحقق'),
        ),
        migrations.AddField(
            model_name='orphan',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='orphan_certs/birth/', verbose_name='شهادة الميلاد'),
        ),
        migrations.AddField(
            model_name='orphan',
            name='death_certificate',
            field=models.FileField(blank=True, null=True, upload_to='orphan_certs/death/', verbose_name='شهادة الوفاة / إثبات الفقد'),
        ),
        migrations.AddField(
            model_name='orphan',
            name='sponsorship_need',
            field=models.CharField(choices=[('Monthly', 'كفالة شهرية شاملة'), ('Financial', 'كفالة مالية (مقطوعة)'), ('Educational', 'كفالة تعليمية'), ('Health', 'كفالة صحية')], default='Monthly', max_length=50, verbose_name='نوع الكفالة المطلوبة'),
        ),
        migrations.AddField(
            model_name='orphan',
            name='story',
            field=models.TextField(blank=True, null=True, verbose_name='القصة والخلفية الإنسانية'),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='gender',
            field=models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orphan',
            name='social_status',
            field=models.CharField(choices=[('يتيم الأب', 'يتيم الأب'), ('يتيم الأم', 'يتيم الأم'), ('يتيم الأبوين', 'يتيم الأبوين'), ('مفقود الأبوين', 'مفقود الأبوين'), ('غير محدد', 'غير محدد')], default='غير محدد', max_length=100),
        ),
    ]
