# Generated by Django 4.2.28 on 2026-03-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_guardian_id_document_orphan_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='is_id_public',
            field=models.BooleanField(default=False, verbose_name='السماح للكافل برؤية الهوية'),
        ),
        migrations.AddField(
            model_name='orphan',
            name='is_birth_cert_public',
            field=models.BooleanField(default=False, verbose_name='السماح للكافل برؤية شهادة الميلاد'),
        ),
        migrations.AddField(
            model_name='orphan',
            name='is_death_cert_public',
            field=models.BooleanField(default=False, verbose_name='السماح للكافل برؤية شهادة الوفاة'),
        ),
    ]
