# Generated by Django 4.2.28 on 2026-03-26 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_guardian_is_id_public_orphan_is_birth_cert_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='orphan',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='source',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رابط التوجيه'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='وقت وتاريخ الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='تمت القراءة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='نص الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان الإشعار'),
        ),
    ]
