# Generated by Django 4.2.28 on 2026-03-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_notification_donor_remove_notification_orphan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='kinship_to_guardian',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صلة القرابة بالوصي'),
        ),
    ]
