# Generated by Django 4.2.28 on 2026-03-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_orphan_kinship_to_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='guardianship_document',
            field=models.FileField(blank=True, null=True, upload_to='orphan_certs/guardianship/', verbose_name='مستند إثبات الوصاية'),
        ),
        migrations.AddField(
            model_name='orphan',
            name='health_report',
            field=models.FileField(blank=True, null=True, upload_to='orphan_certs/health/', verbose_name='التقرير الطبي'),
        ),
        migrations.AddField(
            model_name='orphan',
            name='is_guardianship_doc_public',
            field=models.BooleanField(default=False, verbose_name='السماح للكافل برؤية مستند الوصاية'),
        ),
        migrations.AddField(
            model_name='orphan',
            name='requested_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='المبلغ المطلوب المخصص (دولار)'),
        ),
    ]
