from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'), 
    path('details/', views.details, name='details'),
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register_view, name='register_view'),
    path('logout/', views.logout_view, name='logout_view'),
    
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-dashboard/orphans/', views.manage_orphans, name='manage_orphans'),
    path('admin-dashboard/donors/', views.manage_donors, name='manage_donors'),
    path('admin-dashboard/sponsorships/', views.manage_sponsorships, name='manage_sponsorships'),
    path('admin-dashboard/payments/', views.manage_payments, name='manage_payments'),
    path('admin-dashboard/notifications/', views.notifications_view, name='notifications'),
    path('admin-dashboard/orphans/add/', views.add_orphan, name='add_orphan'),
    path('admin-dashboard/orphans/<int:orphan_id>/', views.admin_orphan_details, name='admin_orphan_details'),
    path('admin-dashboard/orphans/<int:orphan_id>/delete/', views.delete_orphan, name='delete_orphan'),
    path('admin-dashboard/donors/add/', views.add_donor, name='add_donor'),
    path('admin-dashboard/donors/<int:donor_id>/edit/', views.edit_donor, name='edit_donor'),
    path('admin-dashboard/donors/<int:donor_id>/delete/', views.delete_donor, name='delete_donor'),
    path('admin-dashboard/profile/', views.edit_profile, name='edit_profile'),

    path('sponsor-dashboard/', views.sponsor_dashboard, name='sponsor_dashboard'),
    path('sponsor/sponsorships/', views.donor_sponsorships, name='donor_sponsorships'),
    path('sponsor/orphans/', views.donor_orphans, name='donor_orphans'),
    path('sponsor/notifications/', views.donor_notifications, name='donor_notifications'),
    path('sponsor/edit-profile/', views.donor_edit_profile, name='donor_edit_profile'),

    path('orphan-dashboard/', views.orphan_dashboard, name='orphan_dashboard'),
    path('orphan/details/', views.orphan_profile, name='orphan_details'),
    path('orphan/documents/', views.orphan_documents, name='orphan_documents'),
    path('orphan/sponsorships/', views.orphan_sponsorships, name='orphan_sponsorships'),
    path('orphan/notifications/', views.orphan_notifications, name='orphan_notifications'),
    path('orphan/edit-profile/', views.orphan_edit_profile, name='orphan_edit_profile'),
    path('notifications/read/<int:notif_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/read-all/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('sponsorship/<int:spon_id>/accept/', views.accept_sponsorship, name='accept_sponsorship'),
    path('sponsorship/<int:spon_id>/reject/', views.reject_sponsorship, name='reject_sponsorship'),
    path('sponsorship/<int:spon_id>/end/', views.end_sponsorship, name='end_sponsorship'),
    path('sponsorship/<int:spon_id>/renew/', views.renew_sponsorship, name='renew_sponsorship'),
    path('sponsorship/<int:spon_id>/delete/', views.delete_sponsorship, name='delete_sponsorship'),
    path('payment/<int:payment_id>/remind/', views.send_payment_reminder, name='send_payment_reminder'),
    path('admin-notification/<int:notif_id>/read/', views.mark_admin_notif_read, name='mark_admin_notif_read'),
    path('admin-notification/<int:notif_id>/delete/', views.delete_admin_notif, name='delete_admin_notif'),
    path('donor-dashboard/payments/', views.donor_payments, name='donor_payments'),
    path('donor-dashboard/payment/<int:payment_id>/checkout/', views.pay_checkout, name='pay_checkout'),
    path('donor-dashboard/sponsorship/<int:spon_id>/pay-now/', views.initiate_sponsorship_payment, name='initiate_sponsorship_payment'),
    path('donor-dashboard/orphan/<int:orphan_id>/sponsor/', views.create_new_sponsorship, name='create_new_sponsorship'),
    path('sponsor-dashboard/notifications/<int:notif_id>/mark-read/', views.mark_donor_notification_read, name='mark_donor_notification_read'),
    path('sponsor-dashboard/notifications/mark-all-read/', views.mark_all_donor_notifications_read, name='mark_all_donor_notifications_read'),
    path('donor-dashboard/payment/<int:payment_id>/stripe/', views.create_stripe_checkout_session, name='create_stripe_checkout_session'),
    path('api/ai-assistant/', views.kafala_ai_assistant, name='kafala_ai_assistant'),
    path('admin-dashboard/orphans/approve/<int:orphan_id>/', views.approve_orphan_request, name='approve_orphan_request'),
    path('admin-dashboard/orphans/reject/<int:orphan_id>/', views.reject_orphan_request, name='reject_orphan_request'),
    ]
